### ISSUE TITLE
고민해결소 Detail 페이지 css 누락 문제

### ISSUE THREAD

**Issue by auhy49** [STFExSavle/with-savle#125]
<img width="374" alt="Screen Shot 2022-03-16 at 8 50 59 PM" src="https://user-images.githubusercontent.com/94885534/158583950-818e0ab9-f204-4ef1-958b-6363f72296cc.png">

투표 결과보기에서 선택 항목에 대한 color와 bold가 누락됐습니다. 확인바랍니다.

**Comment by talentforest** [comment]
오늘 담당자님이랑 회의할때까지만 해도 있었던거죠? 제가 PR하니까 바뀐건가요?

**Comment by auhy49** [comment]
> 오늘 담당자님이랑 회의할때까지만 해도 있었던거죠? 제가 PR하니까 바뀐건가요?

아뇨 회의때도 스타일 적용이 안됐었어요.. 어디서 빠졌나봐요

**Comment by talentforest** [comment]
아하 알겠습니다. 수정해놓겠습니다~~
