### ISSUE TITLE
투표하기 후 댓글 보이기 기능 

### ISSUE THREAD

**Issue by mrlee323** [STFExSavle/with-savle#133]
투표하고 나서 댓글 보이는 기능 구현 하실건가요 ?
지금은 투표하고나서 토글을 눌러야 댓글을 볼수있는데
처음 기획은 일단 투표하고 댓글이 보이는 기획이었습니다

어떻게 할까요 ???

**Comment by auhy49** [comment]
구현에 큰 문제 없다면 보이는 게 어떨까요?

**Comment by talentforest** [comment]
아 수정해서 구현은 했는데... 투표 완료된 상태에서 새로고침하면 다시 토글이 꺼지네요... 일단 PR은 하겠습니다!

**Comment by auhy49** [comment]
해결했습니다~
