### ISSUE TITLE
투표하기 기능 API 누락

### ISSUE THREAD

**Issue by auhy49** [STFExSavle/with-savle#16]
@talentforest 

사용자가 투표를 하면 count 증가가 되는 api가 누락됐습니다.
주소는 `/api/vote/${id}`이고 PUT 호출로 제작하고 있습니다.

만드는대로 말씀 드리겠습니다

**Comment by talentforest** [comment]
넵 확인했습니다~

**Comment by auhy49** [comment]
> 넵 확인했습니다~

#17 제작했습니다. 말씀드린 `/api/vote/${id}` 가 아닌 `PUT /api/vote`입니다.
axios의 두번째 인자인 params에 투표 ID가 아닌 **투표 항목 ID**가 들어갑니다. 

노션에 있는 API명세서에 추가해놨습니다 🙌
