### ISSUE TITLE
목표공유 페이지 드롭다운 이슈

### ISSUE THREAD

**Issue by mrlee323** [STFExSavle/with-savle#162]
드롭다운 오래된순으로 선택하면 겹치네요 
저만 그렇게 보이는건지는 잘모르겠어요 

![image](https://user-images.githubusercontent.com/92876884/158834512-b90138ea-c009-4c47-9751-5ad341f8bdac.png)

**Comment by maddrake220** [comment]
저는 괜찮은데 혹시 어떤 기종에서 그런 걸까요?

**Comment by mrlee323** [comment]
아이폰 12 미니입니다

**Comment by talentforest** [comment]
헉 저도 그렇네요 저는 아이폰 SE입니다.

**Comment by maddrake220** [comment]
혹시 아직도 그런가요?

**Comment by mrlee323** [comment]
아직도 조금 겹칩니다 
![image](https://user-images.githubusercontent.com/92876884/158987453-d54075c9-896e-48a5-b0e1-95afe9309ace.png)

**Comment by maddrake220** [comment]
기본 ui 초기화하고 새로 만들어야겠네요 확인 감사합니다!
