### ISSUE TITLE
모바일 목표 메인 이슈

### ISSUE THREAD

**Issue by mrlee323** [STFExSavle/with-savle#171]
![image](https://user-images.githubusercontent.com/92876884/158972275-818daaf2-88dd-4541-b8b5-33296c6ebb9b.png)

더많은 목표보러가기
추천목표보러가기
버튼이 없어졌습니다

제 핸드폰 기종은 아이폰 12 미니입니다

**Comment by auhy49** [comment]
제가 고쳤습니다. #172

**Comment by mrlee323** [comment]
넵 감사합니다
