### ISSUE TITLE
Navbar position 으로 인한 issue

### ISSUE THREAD

**Issue by mrlee323** [STFExSavle/with-savle#23]
저축페이지에서 제가 상단쪽에 margin을 줬는데 Navbar와 겹쳐집니다

![image](https://user-images.githubusercontent.com/92876884/156895077-391a225b-42c2-4235-8023-187be4abb1cb.png)

제가 적용을 잘못한건지 
layout에 준 margin-top이 적용이 안되는건지 잘 모르겠습니다
다른분들은 적용이 잘 되었나요 ?

**Comment by auhy49** [comment]
<img width="932" alt="Screen Shot 2022-03-06 at 3 18 59 PM" src="https://user-images.githubusercontent.com/94885534/156911802-b1bf6637-c3d1-472b-85a6-f9c5ba878b26.png">

저는 현재 이렇게 보입니다.
새벽에 PR 주실 때 해결하고 주신 건지요? 아니면 PR 끝난 이후에 발생한 문제일까요?

**Comment by mrlee323** [comment]
PR준 상태에서 발생한 문제입니다.  아직 PR 이후 추가작업은 안한 상태입니다.  지금 주신 캡쳐도 margin과 navbar가 겹치는 것같은데 다른 분들 페이지는 제가 오류가 나서 안보여서 확인이 불가능하네요.

**Comment by auhy49** [comment]
다른 분들 코드도 마찬가지로 margin-top을 주면 navbar와 겹치고 있긴 한데 margin-top 자체를 사용 안하셨네요.
해당 상황에서 padding 줘서 해결하면 어떨까요?

일단 develop 브랜치 최신으로 유지했으니 다른 분들 페이지 오류 나는 것은 새로 pull 하시면 해결될듯합니다

**Comment by auhy49** [comment]
혹은 margin-top을 사용하시려면 navbar 사이즈인 52px 더해서 주시면 될 거 같아요..

현재 navbar는 fixed으로 떠 있는 상태입니다.

**Comment by mrlee323** [comment]
혹시 layout에서  52px div를 하나 더 만드는건 어떨까요 그러면 각페이지에서 따로 margin-top을 따로 더하지 않아도 될듯합니다

**Comment by mrlee323** [comment]
지금 figma를 보니 저축페이지만 margin-top이 필요하네요 제가 52px 더하겠습니다. 확인 감사합니다

**Comment by auhy49** [comment]
아니에요 layout에서 main 박스에 margin-top 값 주고 있습니다. 따로 추가 하지 않으셔도 괜찮습니다.

**Comment by auhy49** [comment]
52px div를 만들게 되면 아래와 같은 스크롤 대응이 가능할까요? 지금 해볼 수 있는 상황이 아니라 모르겠네요... 😢
<img width="982" alt="Screen Shot 2022-03-07 at 12 23 06 PM" src="https://user-images.githubusercontent.com/94885534/156962592-5a7af4d0-5072-4148-88a9-2f3d2bb786c8.png">

**Comment by mrlee323** [comment]
아 제 말은 제 페이지에 추가한다는 말이었습니다. 따로 변경 안하셔도 될듯합니다 제페이지에만 적용되는 부분이라서 padding으로 대체하려고 합니다

**Comment by auhy49** [comment]
> 아 제 말은 제 페이지에 추가한다는 말이었습니다. 따로 변경 안하셔도 될듯합니다 제페이지에만 적용되는 부분이라서 padding으로 대체하려고 합니다

넵 알겠습니다. 다른 문제 있으면 언제든지 말씀해주세요!

**Comment by mrlee323** [comment]
감사합니다 !
