### ISSUE TITLE
목표 & 투표 페이지 에러 

### ISSUE THREAD

**Issue by mrlee323** [STFExSavle/with-savle#28]
최신으로 pull 을 다했는데 아직도 오류 페이지가 뜨네요 
다른 분들은 잘 나오나요 
저만 이렇게 보이는 건가요?

![image](https://user-images.githubusercontent.com/92876884/156969928-55a2bd62-9416-4413-ad07-cf38ea2e8e00.png)

**Comment by talentforest** [comment]
목표 공유 페이지에 들어가셨을 때 바로 저렇게 오류 페이지가 뜨시는 건가요? 저는 에러 나지는 않는데요...😥

**Comment by mrlee323** [comment]
네네 저도 어느 부분이 문제인지를 모르겠어요

**Comment by talentforest** [comment]
> 네네 저도 어느 부분이 문제인지를 모르겠어요

혹시 포트가 3001로 되어있는데 3001은 맞으실까요?

**Comment by mrlee323** [comment]
> > 네네 저도 어느 부분이 문제인지를 모르겠어요
> 
> 혹시 포트가 3001로 되어있는데 3001은 맞으실까요?

아! 3000으로 열었더니 됩니다. 감사합니다 !!

**Comment by talentforest** [comment]
> > > 네네 저도 어느 부분이 문제인지를 모르겠어요
> > 
> > 
> > 혹시 포트가 3001로 되어있는데 3001은 맞으실까요?
> 
> 아! 3000으로 열었더니 됩니다. 감사합니다 !!

넵넵! 아마 서버에서 3000으로 맞춰놓으신게 아닐까요 ㅎㅎ 다행이에욥

**Comment by mrlee323** [comment]
감사합니다!!
