### ISSUE TITLE
서버 500 에러

### ISSUE THREAD

**Issue by talentforest** [STFExSavle/with-savle#29]
<img width="614" alt="스크린샷 2022-03-07 오후 4 06 44" src="https://user-images.githubusercontent.com/91457443/156984273-e95c86c5-ee15-469a-b63c-789c7a2b9f12.png">
<img width="467" alt="스크린샷 2022-03-07 오후 4 06 52" src="https://user-images.githubusercontent.com/91457443/156984335-debec533-4ae4-4124-a6d9-8fd6c09031a5.png">

지금 저축 페이지에서 계속 코드 500 뜨는데 데이터베이스에 뭔가 접근이 안되는 것 같아요. 확인 부탁드립니다😥

**Comment by talentforest** [comment]
헉 갑자기 됐습니다. 감사합니다;;;;;; 뭐가 문제였던 건지;;

**Comment by auhy49** [comment]
저도 문제없네요.. 인터넷 이슈 있다고 하셨는데 DB서버랑 통신이 안된 거 아닐까요?

**Comment by talentforest** [comment]
> 

그랬나봐요. 지금 인터넷 됐다 안됐다 해서..ㅠ 감사합니다! ㅎㅎ
