### ISSUE TITLE
comment  api get 오류

### ISSUE THREAD

**Issue by mrlee323** [STFExSavle/with-savle#46]
comment data를 받으려고 하다가 안돼서 
데이터 확인하려고 봤는데 이런오류가 뜨네요 

![image](https://user-images.githubusercontent.com/92876884/157409922-c3be05f2-d194-4ac8-8efd-27a11ab87a73.png)

id에 parent id 넣으면 돼는거 아닌가요 ??
제가 잘못하고있는건가요 ??

**Comment by auhy49** [comment]
일단 주소가 잘못됐어요! api/vote/comment/[id]입니다.

들어가는건 parentId가 맞고, 숫자타입으로 입력하셔야합니다

**Comment by mrlee323** [comment]
아 슬러시 포함 이군요
API명세서에는 슬러시가 없어서 저도 좀 이상하긴했습니다 
빠른 확인 감사합니다!! 

> 일단 주소가 잘못됐어요! api/vote/comment/[id]입니다.
> 
> 들어가는건 parentId가 맞고, 넘버타입으로 입력하셔야합니다

**Comment by auhy49** [comment]
> 

에고 죄송합니다 제가 잘못적었네요
수정해놨습니다
