### ISSUE TITLE
목표공유 페이지 배포환경 테스팅

### ISSUE THREAD

**Issue by maddrake220** [STFExSavle/with-savle#51]
배포 환경에서 SSG + CSR 테스팅 결과
페이지 소스보기에서 새로운 글 목록이 나타나지 않음 -> SEO에 좋지 못함

제가 생각한 해결 방안

1. revalidate 로 해결: 간격 604800(일주일)로 주기 -> 일주일 간격으로 html을 재 빌드하여 SEO 해결 가능
2. SSR + CSR로 변경: 데이터가 자주 변경되지는 않을 것으로 예상되는데 과한 비용을 지불하는것 같습니다.
3. 리스트페이지는 전부 CSR로 해결후 detail페이지만 ssr로 변경
4. 더 좋은 방법이 있을까요? 

어떤 방법으로 할지 의견주시면 감사하겠습니다!

**Comment by auhy49** [comment]
@talentforest 고민해결소 리스트 페이지도 해당 이슈 결과대로 진행하는게 좋을 거 같습니다.

1. revalidate : 현재 상황에서 가장 괜찮아 보입니다. 내용은 실시간으로 보이고 해당 html만 1주 간격으로 빌드 하게 되겠네요
2. 과한 비용에 동감합니다.
3. detail 페이지는 paths 사용 중이기에 굳이 SSR 사용할 필요는 없다고 생각합니다.

다른 분들도 의견 부탁드려요🙏

**Comment by gum4019** [comment]
저도 진수님 말씀처럼 현재 상황에서 revalidate가 가장 좋을 거 같습니다!

**Comment by auhy49** [comment]
> 1. revalidate

다시 생각해보니 1번 상황에서 SSG와 CSR을 같이 사용한다는 말씀이시죠? 걱정되는게, 이렇게 진행 한다면 SSG 빌드시에 생성될 컴포넌트 하고 CSR 방식에 렌더링 될 컴포넌트 총 두개를 짜야하는 상황 아닐까요?

**Comment by maddrake220** [comment]
네 같은 컴포넌트에 데이터만 CSR로 교체되는 방식입니다!

**Comment by auhy49** [comment]
> 네 같은 컴포넌트에 데이터만 CSR로 교체되는 방식입니다!

SSG 페이지 로딩이 끝나고 CSR 데이터로 대체되는 그 순간만 잘 해결된다면 좋은 방법이겠네요

**Comment by maddrake220** [comment]
solved
