### ISSUE TITLE
Comment API GET 오류

### ISSUE THREAD

**Issue by mrlee323** [STFExSavle/with-savle#60]
```js
export const fetchGetCommentById = async (id) => await axios.get(`${server}/api/goal/comment/${id}`);
```
제가 useSwr을 사용한는데 
```js
 const { data, mutate } = useSWR( `${server}/api/${value}/comment/${id}`,fetcher,);
```
위 주소를 사용합니다 

```js
const fetcher = async (url) => {
  const response = await axios.get(url);
  return response.data.results;
};
```
useSWR에서 fetcher에서 axios를 사용합니다
주신 fetch함수로 useSWR을 어떻게 사용해야할지 모르겠습니다
useSWR을 첫번째 인자로 url을 받고 fetcher에서 데이터를 받는 로직인거 같습니다.
혹시 주소 수정 부탁 드려도 될까요 ? 아님 혹시 주신 함수로 받는 방법 아실까요 ??

**Comment by mrlee323** [comment]
이슈 수정했습니다 조건부는 해결했는데 fetch을  어떻게 사용해야 할지 모르겠어요

**Comment by auhy49** [comment]
useSwr의 콜백함수인 fetcher 함수만 수정하면 어떨까요?

`
const fetcher = async (url) => {
    if(value === "goal"){
      const res = await fetchGetGoalCommentById(id)
      return res.data.results;
    }
    if(value === "vote"){
      const res = await fetchGetVoteCommentById(id)
      return res.data.results;
    }
};
`

**Comment by mrlee323** [comment]
> useSwr의 콜백함수인 fetcher 함수만 수정하면 어떨까요?
> 
> ```
> const fetcher = async (url) => {
>     if(value === "goal"){
>       const res = await fetchGetGoalCommentById(id)
>       return res.data.results;
>     }
>     if(value === "vote"){
>       const res = await fetchGetVoteCommentById(id)
>       return res.data.results;
>     }
> };
> ```

죄송해요 아까 이슈는 해결해서 수정했는데  댓글로 다시 작성할 걸 수정했네요

**Comment by mrlee323** [comment]
> 죄송해요 아까 이슈는 해결해서 수정했는데 댓글로 다시 작성할 걸 수정했네요

**Comment by auhy49** [comment]
아닙니다! fetch를 어떻게 사용해야 할지 모르겠다고 하셨는데 어떤 문제일까요?

**Comment by mrlee323** [comment]
```js
export const fetchGetCommentById = async (id) => await axios.get(`${server}/api/goal/comment/${id}`);
```
을 사용하려고 했는데 useSWR 에서는 주소만 첫번째 인자로 받아서 
```js
`${server}/api/goal/comment/${id}`
```
만 필요합니다

**Comment by auhy49** [comment]
제가 fetch 함수를 수정하는 게 낫겠네요..

일단 이슈 계속 열어두시고 제가 정리 좀 한 다음 월요일에 말씀드려도 될까요?

**Comment by mrlee323** [comment]
넵! 늦으시간 고생하십니다!!   감사합니다
