### ISSUE TITLE
useLike Hook 관련

### ISSUE THREAD

**Issue by auhy49** [STFExSavle/with-savle#62]
```js
    const arrlikes = [];
    const newLikes = [];
    if (likes !== null) {
      arrlikes = likes.split(",");
    }
    if (like) {
      newLikes = arrlikes.filter((value) => value.toString() !== id.toString());
      setLikeNums((like) => (like = like - 1));
    } else {
      newLikes = [...arrlikes, id];
      setLikeNums((like) => (like = like + 1));
    }
```

let -> const으로 변환하면서 arrlikes, newLikes 재할당 부분에서 오류가 나는데, 어떻게 수정하셨을까요?
고민해결소 부분에서도 해당 Hook을 사용해야 하기에 여쭤봅니다!

**Comment by maddrake220** [comment]
const arrlikes = [];
    const newLikes = [];
    if (likes !== null) {
      arrlikes.push(likes.split(","));
    }
    if (like) {
      newLikes.push(
        arrlikes.filter((value) => value.toString() !== id.toString()),
      );
      setLikeNums((like) => (like = like - 1));
    } else {
      newLikes.push([...arrlikes, id]);
      setLikeNums((like) => (like = like + 1));
    }
    이렇게 해결했습니다!

**Comment by auhy49** [comment]
> const arrlikes = []; const newLikes = []; if (likes !== null) { arrlikes.push(likes.split(",")); } if (like) { newLikes.push( arrlikes.filter((value) => value.toString() !== id.toString()), ); setLikeNums((like) => (like = like - 1)); } else { newLikes.push([...arrlikes, id]); setLikeNums((like) => (like = like + 1)); } 이렇게 해결했습니다!

확인 감사합니다. 급한 대로 먼저 수정해놓고 작업하겠습니다~
