### ISSUE TITLE
vote/[id].js height 버그

### ISSUE THREAD

**Issue by auhy49** [STFExSavle/with-savle#72]
<img width="977" alt="Screen Shot 2022-03-13 at 11 04 52 PM" src="https://user-images.githubusercontent.com/94885534/158063308-341bdca0-4a5d-4c68-949b-9782c2f1d6d1.png">

Comment 연결하게 되면 화면 깨지는 버그가 있습니다.

**Comment by talentforest** [comment]
넵! 수정했습니다~

**Comment by talentforest** [comment]
이 부분 그림자지는 해당 container에 `min-height: 100vh;` 값을 주니 해결되었습니다! @gum4019 한번 확인해주세요!~~
