### ISSUE TITLE
Comment.js 관련

### ISSUE THREAD

**Issue by auhy49** [STFExSavle/with-savle#79]
미림님이 작성하신 comment.js 내부에 setCount를 작성했었습니다.

오류가 있어서 Comment 내부에 useEffect를 사용해야 오류가 사라지는데, 코드가 지저분해질까 걱정되네요

```js
useEffect(() => {
  if (!hidden) {
      setCount(data.length);
  }
});
```

해당 코드가 comment.js 내부에 들어가야 합니다.

어떻게 넣는게 가장 이상적일까요?

**Comment by auhy49** [comment]
<img width="436" alt="Screen Shot 2022-03-14 at 7 03 18 PM" src="https://user-images.githubusercontent.com/94885534/158150104-7a4dfa7e-cd13-4a03-bfd0-82fe4274c2c6.png">

추가로, comment 입력시에 key값 오류가 나던 것은 data가 Input값으로 잠깐 변경되면서 comment.id 값이 없어 key 오류가 발생했었네요.

**Comment by mrlee323** [comment]
setCount를 submit 할때 주면 되지않을까요 ??

**Comment by auhy49** [comment]
> setCount를 submit 할때 주면 되지않을까요 ??

useCommentInput.js 말씀이시죠? 지금 확인해봤더니 그렇게 되면 depth가 너무 깊어지는데 괜찮을까요..
