### ISSUE TITLE
style 폴더 위치 변경

### ISSUE THREAD

**Issue by auhy49** [STFExSavle/with-savle#80]
```js
// before
import style from "styles/GoalId.module.scss";

// after
import style from "@/styles/GoalId.module.scss";
```

피드백 받은 것처럼 아래처럼 변경하고, 최상단에 위치한 styles 폴더를 src 내부에 넣으려고 합니다.
각자 폴더 이동하시고 담당 페이지의 import 주소 변경하려고 하는데, 다른 의견 있으신 분 계실까요

**Comment by talentforest** [comment]
아니요! 좋습니다~ 그럼 일단 지금은 최상단의 styles폴더에 다 넣고 작업한다음, 내일 다시 진수님이 src으로 옮겨주시면 import 주소에 "@/~" 추가해서 다시 PR드리면 될까요?

**Comment by auhy49** [comment]
> 아니요! 좋습니다~ 그럼 일단 지금은 최상단의 styles폴더에 다 넣고 작업한다음, 내일 다시 진수님이 src으로 옮겨주시면 import 주소에 "@/~" 추가해서 다시 PR드리면 될까요? 아니면 지금 각자 styles폴더를 src폴더 안에 넣을까요?

옮기게 된다면 경로 설졍 때문에 각자 이동시키는 게 좋을 거 같습니다..

**Comment by talentforest** [comment]
> 

아 그렇군요~ 알겠습니다. 지금 src폴더 안에 styles 폴더 이동하고 그 안에 scss module파일 넣겠습니다~!

**Comment by talentforest** [comment]
저 styles폴더 통채로  옮기니까 어느 경로가 이상한지 못찾겠어요…😢 layout파일에서 에러나는데… 다른 분들은 잘 해결되셨나요?
<img width="389" alt="스크린샷 2022-03-14 오후 7 51 40" src="https://user-images.githubusercontent.com/91457443/158157958-2c8ae638-7190-4105-a487-50e422dde979.png">

**Comment by auhy49** [comment]
아.. 전체를 옮기면 다른분들 경로도 잡아줘야겠네요 ㅠㅠ 
src/styles에 폴더 새로 생성하시고 각자 관리했던 폴더만 옮기는게 어떨까요?

**Comment by talentforest** [comment]
넵 알겠습니다!~
