### ISSUE TITLE
vote 항목 css 관련

### ISSUE THREAD

**Issue by talentforest** [STFExSavle/with-savle#82]
<img width="389" alt="스크린샷 2022-03-14 오후 10 32 27" src="https://user-images.githubusercontent.com/91457443/158182282-61aa5d53-0828-4cb5-9c70-207739436004.png">

혹시 이 부분 너비가 280px 정도일 때 겹치는데 css 수정해야 할까요?
글자수는 저 글자수를 최대 수로 설정해 놓았습니다.

**Comment by auhy49** [comment]
저 상태라 글자수 최대라면, 라디오 버튼 있던 공간을 활용하는건 어떨까요?

**Comment by talentforest** [comment]
아 그럼 저 부분만 미디어쿼리 max-width 280으로 해결해 보겠습니다...!

**Comment by auhy49** [comment]
> 아 그럼 저 부분만 미디어쿼리 max-width 280으로 해결해 보겠습니다...!

네 280px이라면 중요도는 낮아보이니까.. 최소한으로 작업 하시고 속성으로 white-space: pre; 부여하는게 좋아보입니다

**Comment by talentforest** [comment]
> > 아 그럼 저 부분만 미디어쿼리 max-width 280으로 해결해 보겠습니다...!
> 
> 네 280px이라면 중요도는 낮아보이니까.. 최소한으로 작업 하시고 속성으로 white-space: pre; 부여하는게 좋아보입니다

넵 감사합니다~
