### ISSUE TITLE
Unhandled Runtime Error Error: timeout of 4000ms exceeded

### ISSUE THREAD

**Issue by talentforest** [STFExSavle/with-savle#93]
<img width="474" alt="스크린샷 2022-03-15 오후 5 43 49" src="https://user-images.githubusercontent.com/91457443/158339600-81e3be11-e544-4d01-becd-52975a713d11.png">

FavoriteCommentShare 부분 아이콘에 `cursor: pointer`를 넣었는데 해당 아이콘에 클릭을 안하고 4초이상 위에 있으면 저런 에러가 발생합니다... 어떻게 해결을 해야 할까요..?

**Comment by auhy49** [comment]
클릭이 된 건 아닐까요? 해당 오류는 fetch 요청 보내고 응답이 4초 이상으로 지연될 때 발생하는 오류입니다

**Comment by talentforest** [comment]
> 클릭이 된 건 아닐까요? 해당 오류는 fetch 요청 보내고 응답이 4초 이상으로 지연될 때 발생하는 오류입니다

아아 그럼 단순히 제 인터넷이 느려서 그런거군요! 감사합니다~!

**Comment by auhy49** [comment]
저희 데이터베이스 서버가 느려서.. 응답 시간이 꽤 걸리는데 해당 옵션을 제가 지우겠습니다. 먼저 수정하시려면 src/api/vote/index.js에 timeout 항목 삭제해주시면 됩니다

**Comment by talentforest** [comment]
아 지금은 또 잘 돼서...! 일단 수정은 안하고 있겠습니다~
